# -- ADDS A TEST
macro(LIDAR_SFM_ADD_TEST)
    set(TEST_NAME "")
    set(DEPENDENCIES "")
    foreach (_ARG ${ARGN})
        if (TEST_NAME STREQUAL "")
            set(TEST_NAME ${_ARG})
        else ()
            set(DEPENDENCIES ${DEPENDENCIES} ${_ARG})
            # message(FATAL_ERROR ${DEPENDENCIES})
        endif ()
    endforeach ()
    add_executable(${TEST_NAME} ${TEST_NAME}.cpp)
    target_link_libraries(${TEST_NAME} PRIVATE gtest_main PUBLIC ${DEPENDENCIES})
    gtest_discover_tests(${TEST_NAME})
endmacro(LIDAR_SFM_ADD_TEST)
